apiVersion: kubernetes.do.crossplane.io/v1alpha1
kind: DOKubernetesCluster
metadata:
  name: gitops-production
spec:
  providerConfigRef:
    name: digitalocean
  forProvider:
    region: ams3
    version: 1.25.4-do.0
    nodePools:
      - size: s-1vcpu-2gb
        count: 1
        name: worker-pool