apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo
spec:
  template:
    spec:
      containers:
        - name: podinfod
          image: thschue/podinfo:0.0.3 # {"$imagepolicy": "flux-system:podinfo-dev"}
