apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: podinfo
spec:
  template:
    spec:
      containers:
        - name: podinfod
          image: ghcr.io/stefanprodan/podinfo:6.2.3 # {"$imagepolicy": "flux-system:podinfo"}