apiVersion: do.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: digitalocean
  namespace: {{ .Release.Namespace }}
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ .Release.Namespace }}
      name: provider-do-secret
      key: token