apiVersion: kubernetes.do.crossplane.io/v1alpha1
kind: DOKubernetesCluster
metadata:
  name: gitops-dev
spec:
  providerConfigRef:
    name: digitalocean
  forProvider:
    region: ams3
    version: 1.25.4-do.0
    nodePools:
      - size: s-2vcpu-2gb
        autoScale: true
        count: 1
        minNodes: 1
        maxNodes: 6
        name: worker-pool
    maintenancePolicy:
      startTime: "00:00"
      day: wednesday
  writeConnectionSecretToRef:
    name: gitops-dev
    namespace: crossplane-system