---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: ingress-nginx-dev
  namespace: crossplane-system
spec:
  # rollbackLimit: 3
  forProvider:
    namespace: ingress-nginx
    chart:
      name: ingress-nginx
      repository: https://kubernetes.github.io/ingress-nginx
    values:
      controller:
        metrics:
          enabled: true
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "10254"
  providerConfigRef:
    name: helm-provider-dev

---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: flagger-dev
  namespace: crossplane-system
spec:
  # rollbackLimit: 3
  forProvider:
    namespace: ingress-nginx
    chart:
      name: flagger
      repository: https://flagger.app
    values:
      prometheus:
        install: true
      meshProvider: nginx
  providerConfigRef:
    name: helm-provider-dev

---
apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: flagger-loadtester-dev
  namespace: crossplane-system
spec:
  # rollbackLimit: 3
  forProvider:
    namespace: ingress-nginx
    chart:
      name: loadtester
      repository: https://flagger.app
    values:
      cmd:
        timeout: 1h
  providerConfigRef:
    name: helm-provider-dev