apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: flux-dev
  namespace: crossplane-system
spec:
  # rollbackLimit: 3
  forProvider:
    namespace: flux-system
    chart:
      name: flux2
      repository: https://fluxcd-community.github.io/helm-charts
  providerConfigRef:
    name: helm-provider-dev