apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: helm-provider-dev
spec:
  credentials:
    source: Secret
    secretRef:
      name: gitops-dev
      namespace: crossplane-system
      key: kubeconfig