apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider-dev
spec:
  credentials:
    source: Secret
    secretRef:
      name: gitops-dev
      namespace: crossplane-system
      key: kubeconfig